### ISSUE TITLE
LoadError: BoundsError: attempt to access 0-element Vector{Int64} at index [1]

### ISSUE THREAD

**Issue by adria-boada** [mfumagalli/ngsJulia#4]
Greetings,

I am using `ngsJulia` to *estimate allele frequency without SNP calling and known sample size*, following the instructions in the [documentation](https://ngsjulia.readthedocs.io/en/latest/ngsPool/#estimate-allele-frequency-without-snp-calling-and-known-sample-size). The options for the commands used were copied from the documentation (with gzipped input and output). I am working with pool sequencing of *Drosophila melanogaster*.

I might have encountered a couple of errors when using the script `$NGSJULIA/ngsPool/ngsPool.jl`. First, `ngsPool.jl` exits prematurely. The script analyses around 99% sites of the first chromosome, 2% sites of the next chromosome and nothing else. I have found these estimates by comparing the amount of lines with said chromosome within the files `input.mpileup.txt` and `--fout test.out.gz`.

The following error was found **almost** at the end of the logs (lines 29 728 to 29 740 out of 29 924 lines in total). It might be related with the premature exit.

```
LoadError: BoundsError: attempt to access 0-element Vector{Int64} at index [1]
Stacktrace:
 [1] getindex(A::Vector{Int64}, i1::Int64)
   @ Base ./essentials.jl:13
 [2] (::var"#5#7")(file::GZipStream)
   @ Main $NGSJULIA/ngsPool/ngsPool.jl:135
 [3] gzopen(f::var"#5#7", args::String)
   @ GZip ~/.julia/packages/GZip/vS3gf/src/gz.jl:217
 [4] open(::Function, ::Vararg{Any})
   @ GZip ~/.julia/packages/GZip/vS3gf/src/gz.jl:213
 [5] top-level scope
   @ $NGSJULIA/ngsPool/ngsPool.jl:35
in expression starting at $NGSJULIA/ngsPool/ngsPool.jl:35
FFFFFFFFFFFFFFFFFFFFFF:FF:FF")Site("2R", 158890, 'T')
```

Moreover, the logs continually return an error saying that the length of the nucleotide sequence is different from the length of the quality sequence in the input file (by inspecting source code). I guess that the fraction next to the error displays the disparity between sequence lengths.

Snippet near the end of the logs, including these errors:

```
Error! conversion:Reads("AAAAAAAAACAACAATAGCTAACAACAATAGCTAACAACAATAGCTAAAACAACAATAGCTAAAAAAAACAACAATAGCTAAAAAAAAAAAAAAAAAA", "FFFFFF:FF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFF")Site("2R", 160108, 'A')
98/43
allSites:22430000; infSites:22430000
Error! conversion:Reads("TTTTTTTTTTTTTTTTTTTTTTTTTTAAATCATATCCGTGGGTTTTTTTTTTTTTTTTTTTTTTTTTTT", ":FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFJFFFFFFFFFFFF:FFFFF")Site("2R", 164137, 'T')
69/53
Error! conversion:Reads("CCCCCCCCCCTTTTGCTTGACCCTTTTGCTTGACTTTTGCTTGACTTTTGCTTGACCCCCCTTTTGCTTGACCTTTTGCTTGACCCCCCTTTTGCTTGACTTTTGCTTGACTTTTGCTTGACCCCCTTTTGCTTGACCCCCCCCCCCCCCCCCCCCCC", "FFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFF:FFFFFFFFFF:F")Site("2R", 164567, 'C')
158/58
Error! conversion:Reads("TCACCGCCCACCTTTTTTTTTTTTTTTTTCACCGCCCACCTTTTTTCACCGCCCACCTTCACCGCCCACCTCACCGCCCACCTTTTTTTCACCGCCCACCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF")Site("2R", 165991, 'T')
139/73
Error! conversion:Reads("AGAGGTCCCCGAGGTCCCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAGGTCCCCGAGGTCCCCAGAGGTCCCCGAGGTCCCCAAAAAAAAAGAGGTCCCCGAGGTCCCCAAAAAAAAAAAAAAAAACCCC", "FFFFF:FFFFFFFFFFFFFFFFFFFJFFF:FFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFF")Site("2R", 166235, 'A')
134/62
allSites:22440000; infSites:22440000
Error! conversion:Reads("AAAAAAAAAAAAAAATTTTTTTTTTTTTTAAT", ":FFFFFFFF::FFFFFF:")Site("2R", 238550, 'A')
32/18
Error! conversion:Reads("AAAAAAAAAAAAATTTTTTTTTTAAAA", "F:F:FFFFFFFFFFFFF")Site("2R", 238633, 'A')
27/17
allSites:22450000; infSites:22450000
allSites:22460000; infSites:22460000
Error! conversion:Reads("ACGATTATTCATCGAGATTTTAAAAAAAAAAAAAAAAAAAAAAAACGATTATTCATCGAGATTTTACGATTATTCATCGAGATTTTAAAAAAAAAACGATTATTCATCGAGATTTTACGATTATTCATCGAGATTTTAAAACGATTATTCATCGAGATTTTAAAAAAAAAA", "FFFFFFFFFFFFFFFFFkFFFFFFFFFFFFFFFFFFFJFFFFFFFFFFF:F")Site("2R", 318740, 'A')
171/51
Error! conversion:Reads("GGGGGGGGGGGGGGAAGAAGAACGCACGGGGGGGGAAGAAGAACGCACGGGGGGGGGGGG", "FFFFJFF:FFFF:FFF:FFFFFFFFFFFFFFFFF")Site("2R", 321182, 'G')
60/34
Error! conversion:Reads("TTGAAAAAATAATTTTTTTGAAAAAATAATGAAAAAATAATTTGAAAAAATAATGAAAAAATAATGAAAAAATAATGAAAAAATAATTGAAAAAATAATGAAAAAATAATGAAAAAATAATGAAAAAATAATGAAAAAATAATTTGAAAAAATAATTGAAAAAATAATGAAAAAATAATGAAAAAATAATGAAAAAATAATTGAAAAAATAATGAAAAAATAATTGAAAAAATAA", "FFFF:FFFFFFFFFFFFF:FFFFFFFFFFFFFFFF")Site("2R", 326053, 'T')
235/35
allSites:22470000; infSites:22470000
Error! conversion:Reads("AAAAAAAAAAAAAAAAATAAAGCTTCATAAAAGTAAAATAAAGCTTCATAAAAGTAAAAAAAAAAA", "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF")Site("2R", 328267, 'A')
66/30
Error! conversion:Reads("TTTTTTTTTTTTTTTTTTTTTTTGCCGCTTATGCTTTTTGCCGCTTATGCTTTTTTTTTTTTTTTGCCGCTTATGCTTGCCGCTTATGCTTTTTTTTTTT", "FFFFFFF:FFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFF")Site("2R", 329649, 'T')
100/52
allSites:22480000; infSites:22480000
allSites:22490000; infSites:22490000
Error! conversion:Reads("ATTTTTAGATTAAAAAAAAAATTTTTAGATTAAAAAAAAAAAATTTTTAGATTAAAAAAAAATTTTTAGATTAAAAATTTTTAGATTAAA", "FFFkFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFF")Site("2R", 376019, 'A')
90/40
```

I did not generate the input "mpileup" file, so I am not acquainted with the options that were used then. I have tried searching some quality sequences in the mpileup, to retrieve problematic lines:

```
2L  5038    T       14      .$.$.$.$.$.$.$..,-27cgacaatgcacgacagaggaagcagaa.-27CGACAATGCACGACAGAGGAAGCAGAA.,-27cgacaatgcacgacagaggaagcagaa. FFFFFF:FFFFFFF
2L      5753    T       70      .,..,,$.,$.,,.,..,,,,,.,.,,.,.,.,,.,,..,..,-55tattgcaatgttcagtgcagcgcaaaatggccgctcaagaaaaggctcgaatata..-55TATTGCAATGTTCAGTGCAGCGCAAAATGGCCGCTCAAGAAAAGGCTCGAATATA,,-55tattgcaatgttcagtgcagcgcaaaatggccgctcaagaaaaggctcgaatata..-55TATTGCAATGTTCAGTGCAGCGCAAAATGGCCGCTCAAGAAAAGGCTCGAATATA,,.,,,,.,.....,,.,,,.,,        FFFFFF:FFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFJFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
2L        89765   G       66      ,,.,-24gaaattgcgtaactcacttctacc..,.,,,,....,,.-24GAAATTGCGTAACTCACTTCTACC.-24GAAATTGCGTAACTCACTTCTACC.-24GAAATTGCGTAACTCACTTCTACC.,-24gaaattgcgtaactcacttctacc.-24GAAATTGCGTAACTCACTTCTACC.,-24gaaattgcgtaactcacttctacc.-24GAAATTGCGTAACTCACTTCTACC.-24GAAATTGCGTAACTCACTTCTACC,-24gaaattgcgtaactcacttctacc,-24gaaattgcgtaactcacttctacc,-24gaaattgcgtaactcacttctacc.-24GAAATTGCGTAACTCACTTCTACC.-24GAAATTGCGTAACTCACTTCTACC.-24GAAATTGCGTAACTCACTTCTACC.,-24gaaattgcgtaactcacttctacc..-24GAAATTGCGTAACTCACTTCTACC,.-24GAAATTGCGTAACTCACTTCTACC,-24gaaattgcgtaactcacttctacc,-24gaaattgcgtaactcacttctacc.-24GAAATTGCGTAACTCACTTCTACC.-24GAAATTGCGTAACTCACTTCTACC.-24GAAATTGCGTAACTCACTTCTACC.-24GAAATTGCGTAACTCACTTCTACC,-24gaaattgcgtaactcacttctacc,-24gaaattgcgtaactcacttctacc,-24gaaattgcgtaactcacttctacc.-24GAAATTGCGTAACTCACTTCTACC,,-24gaaattgcgtaactcacttctacc,-24gaaattgcgtaactcacttctacc.-24GAAATTGCGTAACTCACTTCTACC,-24gaaattgcgtaactcacttctacc.-24GAAATTGCGTAACTCACTTCTACC.-24GAAATTGCGTAACTCACTTCTACC,.-24GAAATTGCGTAACTCACTTCTACC,-24gaaattgcgtaactcacttctacc.-24GAAATTGCGTAACTCACTTCTACC,-24gaaattgcgtaactcacttctacc.-24GAAATTGCGTAACTCACTTCTACC,-24gaaattgcgtaactcacttctacc.,        FFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFF
```

I think that these lines are the problem because the quality sequence matches. Furthermore, the site column of the mpileup and "allSites" in the logs also match.

What I saw different from the rest of the input lines was the `-24GAAATTGCGTAACTCACTTCTACC` fragments (which I guess are insertions/deletions?).

Any help would be greatly appreciated. Sincerely,
Adrià.

**Comment by mfumagalli** [comment]
Dear Adria',

thanks for the accurate reporting of the issue.

You are right as, at the moment, ngsJulia doesn't handle insertion/deletions longer than 9 base pairs. Can you please remove such long indels from your data and check whether ngsJulia complains again? You can filter out the whole variant (entry in mpileup) as a quick fix. Anyway, ngsJulia will ignore such indels in its calculations.

Time permitted (and if there is the need) I will implement the parsing of longer indels.

Thank you

Matteo
________________________________
From: adria-boada ***@***.***>
Sent: 18 September 2024 11:39 AM
To: mfumagalli/ngsJulia ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mfumagalli/ngsJulia] LoadError: BoundsError: attempt to access 0-element Vector{Int64} at index [1] (Issue #4)


Greetings,

I am using ngsJulia to estimate allele frequency without SNP calling and known sample size, following the instructions in the documentation<https://ngsjulia.readthedocs.io/en/latest/ngsPool/#estimate-allele-frequency-without-snp-calling-and-known-sample-size>. The options for the commands used were copied from the documentation (with gzipped input and output). I am working with pool sequencing of Drosophila melanogaster.

I might have encountered a couple of errors when using the script $NGSJULIA/ngsPool/ngsPool.jl. First, ngsPool.jl exits prematurely. The script analyses around 99% sites of the first chromosome, 2% sites of the next chromosome and nothing else. I have found these estimates by comparing the amount of lines with said chromosome within the files input.mpileup.txt and --fout test.out.gz.

The following error was found almost at the end of the logs (lines 29 728 to 29 740 out of 29 924 lines in total). It might be related with the premature exit.

LoadError: BoundsError: attempt to access 0-element Vector{Int64} at index [1]
Stacktrace:
 [1] getindex(A::Vector{Int64}, i1::Int64)
   @ Base ./essentials.jl:13
 [2] (::var"#5#7")(file::GZipStream)
   @ Main $NGSJULIA/ngsPool/ngsPool.jl:135
 [3] gzopen(f::var"#5#7", args::String)
   @ GZip ~/.julia/packages/GZip/vS3gf/src/gz.jl:217
 [4] open(::Function, ::Vararg{Any})
   @ GZip ~/.julia/packages/GZip/vS3gf/src/gz.jl:213
 [5] top-level scope
   @ $NGSJULIA/ngsPool/ngsPool.jl:35
in expression starting at $NGSJULIA/ngsPool/ngsPool.jl:35
FFFFFFFFFFFFFFFFFFFFFF:FF:FF")Site("2R", 158890, 'T')


Moreover, the logs continually return an error saying that the length of the nucleotide sequence is different from the length of the quality sequence in the input file (by inspecting source code). I guess that the fraction next to the error displays the disparity between sequence lengths.

Snippet near the end of the logs, including these errors:

Error! conversion:Reads("AAAAAAAAACAACAATAGCTAACAACAATAGCTAACAACAATAGCTAAAACAACAATAGCTAAAAAAAACAACAATAGCTAAAAAAAAAAAAAAAAAA", "FFFFFF:FF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFF")Site("2R", 160108, 'A')
98/43
allSites:22430000; infSites:22430000
Error! conversion:Reads("TTTTTTTTTTTTTTTTTTTTTTTTTTAAATCATATCCGTGGGTTTTTTTTTTTTTTTTTTTTTTTTTTT", ":FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFJFFFFFFFFFFFF:FFFFF")Site("2R", 164137, 'T')
69/53
Error! conversion:Reads("CCCCCCCCCCTTTTGCTTGACCCTTTTGCTTGACTTTTGCTTGACTTTTGCTTGACCCCCCTTTTGCTTGACCTTTTGCTTGACCCCCCTTTTGCTTGACTTTTGCTTGACTTTTGCTTGACCCCCTTTTGCTTGACCCCCCCCCCCCCCCCCCCCCC", "FFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFF:FFFFFFFFFF:F")Site("2R", 164567, 'C')
158/58
Error! conversion:Reads("TCACCGCCCACCTTTTTTTTTTTTTTTTTCACCGCCCACCTTTTTTCACCGCCCACCTTCACCGCCCACCTCACCGCCCACCTTTTTTTCACCGCCCACCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT", "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF")Site("2R", 165991, 'T')
139/73
Error! conversion:Reads("AGAGGTCCCCGAGGTCCCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAGGTCCCCGAGGTCCCCAGAGGTCCCCGAGGTCCCCAAAAAAAAAGAGGTCCCCGAGGTCCCCAAAAAAAAAAAAAAAAACCCC", "FFFFF:FFFFFFFFFFFFFFFFFFFJFFF:FFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFF")Site("2R", 166235, 'A')
134/62
allSites:22440000; infSites:22440000
Error! conversion:Reads("AAAAAAAAAAAAAAATTTTTTTTTTTTTTAAT", ":FFFFFFFF::FFFFFF:")Site("2R", 238550, 'A')
32/18
Error! conversion:Reads("AAAAAAAAAAAAATTTTTTTTTTAAAA", "F:F:FFFFFFFFFFFFF")Site("2R", 238633, 'A')
27/17
allSites:22450000; infSites:22450000
allSites:22460000; infSites:22460000
Error! conversion:Reads("ACGATTATTCATCGAGATTTTAAAAAAAAAAAAAAAAAAAAAAAACGATTATTCATCGAGATTTTACGATTATTCATCGAGATTTTAAAAAAAAAACGATTATTCATCGAGATTTTACGATTATTCATCGAGATTTTAAAACGATTATTCATCGAGATTTTAAAAAAAAAA", "FFFFFFFFFFFFFFFFFkFFFFFFFFFFFFFFFFFFFJFFFFFFFFFFF:F")Site("2R", 318740, 'A')
171/51
Error! conversion:Reads("GGGGGGGGGGGGGGAAGAAGAACGCACGGGGGGGGAAGAAGAACGCACGGGGGGGGGGGG", "FFFFJFF:FFFF:FFF:FFFFFFFFFFFFFFFFF")Site("2R", 321182, 'G')
60/34
Error! conversion:Reads("TTGAAAAAATAATTTTTTTGAAAAAATAATGAAAAAATAATTTGAAAAAATAATGAAAAAATAATGAAAAAATAATGAAAAAATAATTGAAAAAATAATGAAAAAATAATGAAAAAATAATGAAAAAATAATGAAAAAATAATTTGAAAAAATAATTGAAAAAATAATGAAAAAATAATGAAAAAATAATGAAAAAATAATTGAAAAAATAATGAAAAAATAATTGAAAAAATAA", "FFFF:FFFFFFFFFFFFF:FFFFFFFFFFFFFFFF")Site("2R", 326053, 'T')
235/35
allSites:22470000; infSites:22470000
Error! conversion:Reads("AAAAAAAAAAAAAAAAATAAAGCTTCATAAAAGTAAAATAAAGCTTCATAAAAGTAAAAAAAAAAA", "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF")Site("2R", 328267, 'A')
66/30
Error! conversion:Reads("TTTTTTTTTTTTTTTTTTTTTTTGCCGCTTATGCTTTTTGCCGCTTATGCTTTTTTTTTTTTTTTGCCGCTTATGCTTGCCGCTTATGCTTTTTTTTTTT", "FFFFFFF:FFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFF")Site("2R", 329649, 'T')
100/52
allSites:22480000; infSites:22480000
allSites:22490000; infSites:22490000
Error! conversion:Reads("ATTTTTAGATTAAAAAAAAAATTTTTAGATTAAAAAAAAAAAATTTTTAGATTAAAAAAAAATTTTTAGATTAAAAATTTTTAGATTAAA", "FFFkFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFF")Site("2R", 376019, 'A')
90/40


I did not generate the input "mpileup" file, so I am not acquainted with the options that were used then. I have tried searching some quality sequences in the mpileup, to retrieve problematic lines:

2L  5038    T       14      .$.$.$.$.$.$.$..,-27cgacaatgcacgacagaggaagcagaa.-27CGACAATGCACGACAGAGGAAGCAGAA.,-27cgacaatgcacgacagaggaagcagaa. FFFFFF:FFFFFFF
2L      5753    T       70      .,..,,$.,$.,,.,..,,,,,.,.,,.,.,.,,.,,..,..,-55tattgcaatgttcagtgcagcgcaaaatggccgctcaagaaaaggctcgaatata..-55TATTGCAATGTTCAGTGCAGCGCAAAATGGCCGCTCAAGAAAAGGCTCGAATATA,,-55tattgcaatgttcagtgcagcgcaaaatggccgctcaagaaaaggctcgaatata..-55TATTGCAATGTTCAGTGCAGCGCAAAATGGCCGCTCAAGAAAAGGCTCGAATATA,,.,,,,.,.....,,.,,,.,,        FFFFFF:FFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFJFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
2L        89765   G       66      ,,.,-24gaaattgcgtaactcacttctacc..,.,,,,....,,.-24GAAATTGCGTAACTCACTTCTACC.-24GAAATTGCGTAACTCACTTCTACC.-24GAAATTGCGTAACTCACTTCTACC.,-24gaaattgcgtaactcacttctacc.-24GAAATTGCGTAACTCACTTCTACC.,-24gaaattgcgtaactcacttctacc.-24GAAATTGCGTAACTCACTTCTACC.-24GAAATTGCGTAACTCACTTCTACC,-24gaaattgcgtaactcacttctacc,-24gaaattgcgtaactcacttctacc,-24gaaattgcgtaactcacttctacc.-24GAAATTGCGTAACTCACTTCTACC.-24GAAATTGCGTAACTCACTTCTACC.-24GAAATTGCGTAACTCACTTCTACC.,-24gaaattgcgtaactcacttctacc..-24GAAATTGCGTAACTCACTTCTACC,.-24GAAATTGCGTAACTCACTTCTACC,-24gaaattgcgtaactcacttctacc,-24gaaattgcgtaactcacttctacc.-24GAAATTGCGTAACTCACTTCTACC.-24GAAATTGCGTAACTCACTTCTACC.-24GAAATTGCGTAACTCACTTCTACC.-24GAAATTGCGTAACTCACTTCTACC,-24gaaattgcgtaactcacttctacc,-24gaaattgcgtaactcacttctacc,-24gaaattgcgtaactcacttctacc.-24GAAATTGCGTAACTCACTTCTACC,,-24gaaattgcgtaactcacttctacc,-24gaaattgcgtaactcacttctacc.-24GAAATTGCGTAACTCACTTCTACC,-24gaaattgcgtaactcacttctacc.-24GAAATTGCGTAACTCACTTCTACC.-24GAAATTGCGTAACTCACTTCTACC,.-24GAAATTGCGTAACTCACTTCTACC,-24gaaattgcgtaactcacttctacc.-24GAAATTGCGTAACTCACTTCTACC,-24gaaattgcgtaactcacttctacc.-24GAAATTGCGTAACTCACTTCTACC,-24gaaattgcgtaactcacttctacc.,        FFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFF


I think that these lines are the problem because the quality sequence matches. Furthermore, the site column of the mpileup and "allSites" in the logs also match.

What I saw different from the rest of the input lines was the -24GAAATTGCGTAACTCACTTCTACC fragments (which I guess are insertions/deletions?).

Any help would be greatly appreciated. Sincerely,
Adrià.

**Comment by adria-boada** [comment]
Dear Matteo,

Now, it makes sense why some sites of the first chromosome would be excluded from the input; the missing <1% would be sites with annotated long indels, which `ngsJulia` would have skipped/ignored.

Because the first error (`LoadError : BoundsError`) is talking about "something gzip" I tried decompressing the mpileup. However, both the compressed and decompressed inputs exited prematurely at the same point.

I will follow your advice on removing sites with any indel or long indels and report back these results.

Thanks for the swift response!
Adrià.

**Comment by adria-boada** [comment]
I have rerun the same task, only excluding all indels from the mpileup.

The intermittent errors due to indels have disappeared. The ones that started with `Error! conversion:Reads`.

However, the task still exits prematurely. The `LoadError:BoundsError` still persists. It appears to occur between printing `allSites:` and the number of "allSites" to the log files. I will paste it once again, although the error message is the same:

```
allSites:18190000; infSites:18190000
allSites:ERROR: LoadError: BoundsError: attempt to access 0-element Vector{Int64} at index [1]
Stacktrace:
 [1] getindex(A::Vector{Int64}, i1::Int64)
   @ Base ./essentials.jl:13
 [2] (::var"#5#7")(file::GZipStream)
   @ Main $NGSJULIA/ngsJulia/ngsPool/ngsPool.jl:135
 [3] gzopen(f::var"#5#7", args::String)
   @ GZip ~/.julia/packages/GZip/vS3gf/src/gz.jl:217
 [4] open(::Function, ::Vararg{Any})
   @ GZip ~/.julia/packages/GZip/vS3gf/src/gz.jl:213
 [5] top-level scope
   @ $NGSJULIA/ngsJulia/ngsPool/ngsPool.jl:35
in expression starting at $NGSJULIA/ngsJulia/ngsPool/ngsPool.jl:35
18200000; infSites:18200000
allSites:18210000; infSites:18210000
```

Then the log files continue until `allSites:22720000; infSites:22720000`. Which would be around the beginning of the next chromosome in the file (the second one).

Could it be that the version of the Gzip package causes problems? I'm clueless. I tried to uncompress the input, but it might be more related to the built-in compression of the output. I could try running the same task but avoiding the `.gz` extension of the output parameters, and ngsJulia should not compress the output, right?

Just to be thorough, the last line of the output is the site 748 931. All of the three runs that I have tried exit prematurely at this output site. I will paste the surrounding sites of the input...

```
2R	748930	A	22	.$..$..,....$.......,,,.,	FFF:FFFF:F:FFFFFFF:FkF
2R	748931	A	13	.$.$.$,$....,,,.,	F::FF::::FFkF
    -- next line of the input is excluded from the output --
2R	748932	N	4	C$C$CC$	:FFQ       <--- produces the error ????
2R	748933	N	1	T	F
2R	748934	N	1	G$	F
2R	763073	T	1	^<.	F
2R	763074	A	1	.	F
2R	763075	A	1	.	F
2R	763076	T	1	.	F
```

**Comment by mfumagalli** [comment]
Thank you for testing this. I am glad to hear that the problem with the indels is solved.

Two possible solutions.


  *
I can see that the potential offending lines have only 1 read. Can you please impose some minimum filtering requiring the per-site coverage to be at least 2? I believe to remember to encounter issues when only 1 read was present. Anyway, there won't be any sensible results with only 1 read.


  *
Did you merge all chromosomes together? If so, can you run each chromosome separately? I don't believe I planned for ngsJulia to be run on multiple chroms seamlessly in my initial prototype.


________________________________

**Comment by adria-boada** [comment]
Good morning,

I have done a few tests. To begin with, I filtered out sites where only a single read mapped. It did not solve the issue. Next, I tried separating the offending chromosome to analyse it on its own, without positive results. Lastly, I looked carefully at the snippet that I sent, where the program exited prematurely. Then I realised that the line causing the error had an ambiguous reference base "N". Thus, I searched for the first occurrence of "N", which was at that line.

Finally, I filtered out lines with ambiguous reference bases and rerun the program. It appears that it solved the error mentioned above!

I am grateful for your support,
Adrià.
